ALTER TABLE settings ADD COLUMN use_minecraft_mirror INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN use_modrinth_mirror INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN use_curseforge_mirror INTEGER NOT NULL DEFAULT TRUE;
