[package]
name = "axolotl-installer-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[build-dependencies]
embed-resource = "3.0.11"

[target."cfg(windows)".dependencies]
base64.workspace = true
native-dialog.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tao = "0.35.3"
wry = "0.55.1"

[lints]
workspace = true
